# Generated by Django 5.0.3 on 2024-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
