# Generated by Django 5.0.3 on 2024-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMarketLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField()),
                ('request_path', models.CharField()),
                ('request_status', models.SmallIntegerField()),
                ('response', models.JSONField()),
            ],
        ),
    ]
